version: '3.0'
services:
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy
    ports: []
    hostname: oauth2-proxy
    command: [
        "--config=/oauth2-proxy.cfg",
        "--client-id=${GITHUB_CLIENT_ID}",
        "--client-secret=${GITHUB_CLIENT_SECRET}",
        "--cookie-secret=${OAUTH2_COOKIE_SECRET}",
        "--whitelist-domain=.keepmywork.com"
    ]
    volumes:
      - ./oauth2-proxy.cfg:/oauth2-proxy.cfg
    networks:
      - oauth2-proxy
  nginx:
    container_name: nginx
    image: nginx:1.18
    ports: []
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      oauth2-proxy:
      common:
        ipv4_address: 192.168.69.69

networks:
  oauth2-proxy:
    driver: bridge
  common:
    external: true
